[build]
rustflags = ["-C", "target-feature=+crt-static"]
target = "armv7-unknown-linux-gnueabihf"

# Set custom linker for the specific target
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"