name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - bme280
          - pmsa003i
          - scd-41

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Add ARM musl target
      run: rustup target add arm-unknown-linux-musleabihf

    - name: Install musl tools and ARM cross-compilation toolchain
      run: sudo apt-get update && sudo apt-get install -y musl-tools gcc-arm-linux-gnueabihf

    - name: Build ${{ matrix.project }} for ARM musl
      run: |
        cd ${{ matrix.project }}
        cargo build --target arm-unknown-linux-musleabihf --release --verbose