name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - bme280
          - pmsa003i

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Add ARM target
      run: rustup target add armv7-unknown-linux-gnueabihf

    - name: Install ARM cross-compilation toolchain
      run: sudo apt-get install -y gcc-arm-linux-gnueabihf

    - name: Build ${{ matrix.project }} for ARM
      run: |
        cd ${{ matrix.project }}
        cargo build --target armv7-unknown-linux-gnueabihf --verbose